
version: "2"
plugins:
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  rubocop:
    enabled: true
  reek:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 35
exclude_patterns:
  - coverage/
  - docs/
  - spec/
