sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.4
  - 2.4.3
  - 2.5.1
env:
  global:
    - CI="travis"
    - CC_TEST_REPORTER_ID=f49d2d642ef584e2851eb50ecc7d8f684b33c3f3d3c55364b6e6d796091deb3b
before_install: gem install bundler -v 1.16.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  ./cc-test-reporter after-build -t simplecov -p /home/travis/build/sandboxws/dark_prism
